site_name: Contrib Tracker
docs_dir: docs
plugins:
  - techdocs-core

nav:
  - Overview: 'index.md'
  - Key Benefits: 'benefits.md'
  - Tools and Pre-requisites: 'custom-plugins/technologies.md'
  - Local Environment Setup: 'local_setup.md'
  - How to Contribute: 'contribute.md'
  - Custom Modules and Themes: 'custom_modules.md'
  - Monitoring and Logging: 'monitoring.md'